### ISSUE TITLE
Громкость и каналы в одном устройстве не будут работать

### ISSUE THREAD

**Issue by jackkum** [popstas/yandex-dialogs-smarthome-mqtt#1]
Вот [тут](https://github.com/popstas/yandex-dialogs-smarthome-mqtt/blob/master/src/device.js#L54) поиск навыка осуществляется по типу, но у громкости и каналов одинаковый тип [devices.capabilities.range](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/range.html) и при изменении громкости, яндекс выдает ошибку. 

Заменил в этой строке `this.getCapabilityByType(capability.type)` на `this.getCapabilityByInstance(capability.state.instance)` и всё пошло отлично.

**Comment by popstas** [comment]
@jackkum, спасибо! Поправил, у меня нет устройств с 2 range, поэтому не натыкался на такое.
